### ISSUE TITLE
Changing Input to MediaLive from HLS pull to Mediaconnecgt

### ISSUE THREAD

**Issue by pcb105** [aws-samples/aws-cdk-mediaservices-refarch#26]
Hello,  

I have run thru this example using the default settings and everything works great.  I am transitioning an SSAI workflow to CDK and I want to use this as a starting point.  

The first change I want to make is to change to a MediaConnect flow.  The input to the flow is SRT TS stream with SCTE35 messages.  I have a working workflow that I setup an HLS output group (Send Live audio, video...... and other AWS Media Services with HTTP Live Streaming)....  I then add ad markers and set to ELEMENTAL_SCTE35.

I updated the configuration json and changed the MediaLive settings:
        "inputType" : "MEDIACONNECT",
        "priUrl": "",
        "secUrl" : "",
        "priFlow" : "arn:aws:mediaconnect:XXXXXXXXXXXX",

The rest of the settings I left the same.     

I deployed.... The video and audio etc all came thru, but I never saw any ads when SCTE messages were sent in the stream.  I went thru and did a quick comparison of the MediaLive settings and I see that instead the example uses MediaPackage as the output group type.  I do not see any settings for SCTE ad markers.  

What is the best way to include ad markers in the output from MediaLive to Mediapackage for this CDK?

**Comment by pcb105** [comment]
Sorry....  The workflow is working properly.  I did not wait enough time.  I will update if there truely is an issue.

**Comment by jamiepmullan** [comment]
@pcb105 - did you need any more help? Or are you happy if I closed this issue?

**Comment by jamiepmullan** [comment]
closing - let us know if you need any additional help
